language: erlang

before_script:
  - kerl list installations

otp_release:
  - 19.2
  - 18.2
  - 17.5

sudo: false
install: true
before_script:
  - make rebar3

script:
  - ./rebar3 xref
  - ./rebar3 dialyzer
  - ./rebar3 ct --suite test/otter_SUITE

branches:
  only:
  - master
  - 0.3.0
